version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: orderDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: simpleUser
      POSTGRES_PASSWORD: password123
    volumes:
      - ./../databases/orderDB:/var/lib/postgresql/data

volumes:
  postgres_data:
